[package]
name = "apt-updates-notifier"
version = "0.1.0"
edition = "2021"
authors = ["Zach Schneider <hello@zacharyschneider.ca>"]
license-file = "LICENCE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
config = { version = "0.13.3", features = ["toml"], default-features = false }
cxx = "1.0.94"
dialoguer = "0.10.4"
lettre = { version = "0.10.4", features = ["serde"] }
nix = { version = "0.26.2", features = ["user", "hostname"], default-features = false }
rust-apt = "0.5.1"
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.4"
#tokio = { version = "1.28.1", features = ["rt"] }

[dev-dependencies]

[package.metadata.deb]
# name = ""
priority = "optional"
section = "utils"
# extended-description-file = "pkg/debian/description.txt"
license-file = ["LICENCE", "0"]
#depends = "$auto, debconf, libssl3"
depends = "$auto, libssl3"
maintainer-scripts = "pkg/debian/"
# changelog = "target/debian/changelog" # this will be generated by the pkg workflow
assets = [
    ["target/release/apt-updates-notifier", "/usr/bin/apt-updates-notifier", "755"],
]

[package.metadata.deb.systemd-units]
unit-name = "apt-updates-notifier"
unit-scripts = "pkg/common"
# enable = false
start = false
restart-after-upgrade = false