#!/bin/sh

# # In case this system is running systemd, we make systemd reload the unit files
# # to pick up changes.
# if [ -d /run/systemd/system ] ; then
# 	systemctl --system daemon-reload >/dev/null || true
# fi

# if [ "$1" = "remove" ]; then
# 	if [ -x "/usr/bin/deb-systemd-helper" ]; then
# 		deb-systemd-helper mask hello.service >/dev/null
# 	fi
# fi

PKG_CONF="/etc/pkg-updates-notifier.conf"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -f ${PKG_CONF} ]; then
        rm ${PKG_CONF}
    fi

    if [ -e /usr/share/debconf/confmodule ]; then
        # Source debconf library.
        . /usr/share/debconf/confmodule
        # Remove my changes to the db.
        db_purge
    fi
    ;;
esac

#DEBHELPER#